### ISSUE TITLE
cannot find package "github.com/vladimirvivien/gosh/api"

### ISSUE THREAD

**Issue by nhatlee** [vladimirvivien/gosh#3]
I got the error when run example by: `go run shell/gosh.go`. The error:
```
shell/gosh.go:15:2: cannot find package "github.com/vladimirvivien/gosh/api" in any of:
	/usr/local/go/src/github.com/vladimirvivien/gosh/api (from $GOROOT)
	/Users/nhatle/go/src/github.com/vladimirvivien/gosh/api (from $GOPATH)
```
The link `github.com/vladimirvivien/gosh/api` have error `404` when run on browser.

**Comment by vladimirvivien** [comment]
Hi @nhatlee 
Apologies for late reply.  I am unable to reproduce this error.
Couple of things when running locally:
- Make sure to clone entire repo
- Run the command above (`go run shell/gosh.go`) from repo's root dir.
